spring.application.name=redsalud
server.port=8080

spring.datasource.url=jdbc:postgresql://hmuj9a5b.us-east.database.insforge.app:5432/insforge?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=af74a64e2f25dd3db55497b40867018e
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect